apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "userdir.fullname" . }}-pgdata
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize | quote }}