apiVersion: v1
kind: Service
metadata:
  name: {{ include "userdir.fullname" . }}-backend
spec:
  selector: { app: {{ include "userdir.fullname" . }}-backend }
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      name: http
  type: {{ .Values.backend.service.type }}