apiVersion: v1
kind: Service
metadata:
  name: {{ include "userdir.fullname" . }}-frontend
spec:
  selector: { app: {{ include "userdir.fullname" . }}-frontend }
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      name: http
  type: {{ .Values.frontend.service.type }}