server.port=8080
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/userdir}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:userdir}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:userdir}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}
spring.sql.init.schema-locations=${SPRING_SQL_INIT_SCHEMA_LOCATIONS:classpath:schema.sql}
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=false